#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : trash-cli
Version  : 0.20.12.26
Release  : 4
URL      : file:///aot/build/clearlinux/packages/trash-cli/trash-cli-0.20.12.26.tar.gz
Source0  : file:///aot/build/clearlinux/packages/trash-cli/trash-cli-0.20.12.26.tar.gz
Summary  : Command line interface to FreeDesktop.org Trash.
Group    : Development/Tools
License  : GPL-2.0
Requires: trash-cli-bin = %{version}-%{release}
Requires: trash-cli-man = %{version}-%{release}
Requires: trash-cli-python = %{version}-%{release}
Requires: trash-cli-python3 = %{version}-%{release}
Requires: Jinja2
Requires: psutil
BuildRequires : Jinja2
BuildRequires : buildreq-distutils3
BuildRequires : psutil
BuildRequires : setuptools-python

%description
trash-cli——FreeDesktop.org 回收站的命令行界面
=============================================

%package bin
Summary: bin components for the trash-cli package.
Group: Binaries

%description bin
bin components for the trash-cli package.


%package man
Summary: man components for the trash-cli package.
Group: Default

%description man
man components for the trash-cli package.


%package python
Summary: python components for the trash-cli package.
Group: Default
Requires: trash-cli-python3 = %{version}-%{release}

%description python
python components for the trash-cli package.


%package python3
Summary: python3 components for the trash-cli package.
Group: Default
Requires: python3-core
Provides: pypi(trash_cli)
Requires: pypi(psutil)

%description python3
python3 components for the trash-cli package.


%prep
%setup -q -n trash-cli
cd %{_builddir}/trash-cli

%build
unset http_proxy
unset https_proxy
unset no_proxy
export SSL_CERT_FILE=/var/cache/ca-certs/anchors/ca-certificates.crt
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1617329033
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=16 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=16 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=16 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=16 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/trash
/usr/bin/trash-empty
/usr/bin/trash-list
/usr/bin/trash-put
/usr/bin/trash-restore
/usr/bin/trash-rm

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/trash-empty.1
/usr/share/man/man1/trash-list.1
/usr/share/man/man1/trash-put.1
/usr/share/man/man1/trash-restore.1
/usr/share/man/man1/trash-rm.1

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
